name: Simple Windows Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      
      - name: Install dependencies
        run: |
          go mod tidy
          go get -u github.com/lxn/walk
          go get -u github.com/lxn/win
      
      - name: Build
        run: |
          go build -o mooc-gui.exe
      
      - name: Create artifact directory
        run: mkdir artifacts
      
      - name: Copy executable
        run: copy mooc-gui.exe artifacts\
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mooc-gui
          path: artifacts\
